### PR TITLE
Added .gcsafe. to wakeupAll, fixes #22

### LINKED ISSUE #22: missing .gcsafe in asyncsync
```
.nimble/pkgs/asynctools-0.1.1/asynctools/asyncsync.nim(159, 15) Error: type mismatch: got <proc (){.closure.}>
but expected one of: 
proc callSoon(cbproc: proc () {.gcsafe.})
  first type mismatch at position: 1
  required type for cbproc: proc (){.closure, gcsafe.}
  but expression 'wakeupAll' is of type: proc (){.closure.}
  This expression is not GC-safe. Annotate the proc with {.gcsafe.} to get extended error information.

expression: callSoon(wakeupAll)
```

### PR DESCRIPTION
**Pull request by zevv**

### CODE REVIEW

**Comment by itsumura-h** [comment]
@cheatfate 
I got an error and found the same solution of this PR. Please merge this PR soon!

**Comment by SolitudeSF** [comment]
@cheatfate any update?

**Comment by timotheecour** [comment]
@zevv no point in keeping both this and https://github.com/cheatfate/asynctools/pull/19 which is the same PR. 

/@cheatfate any way you could merge the open PR's ?

**Comment by timotheecour** [comment]
we should close this now that https://github.com/cheatfate/asynctools/pull/19 was merged

**Pull request closed without merging**
